# Generated by Django 4.0.5 on 2022-07-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка')),
                ('link_auto_ru', models.URLField(verbose_name='Ссылка на auto.ru')),
            ],
            options={
                'db_table': 'car_brand',
            },
        ),
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Объём')),
                ('power', models.IntegerField(verbose_name='Мощность л.с.')),
                ('oil_type', models.CharField(choices=[('PETROL', 'Бензин'), ('DIESEL', 'Дизель'), ('HYBRID', 'Гибрид'), ('GAZ', 'Газ'), ('ELECTRICITY', 'Электрический')], max_length=15, verbose_name='Тип топлива')),
                ('acceleration', models.IntegerField(verbose_name='Разгон до 100 км/ч, сек.')),
            ],
            options={
                'db_table': 'car_engine',
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Поколение')),
                ('body_type', models.CharField(choices=[('SEDAN', 'Седан'), ('HATCHBACK_3_DOOR', 'Хэтчбэк 3 дв.'), ('HATCHBACK_5_DOOR', 'Хэтчбэк 5 дв.'), ('LIFTBACK', 'Лифтбэк'), ('ALLROAD_3_DOOR', 'Внедорожник 3 дв.'), ('ALLROAD_5_DOOR', 'Внедорожник 5 дв.'), ('WAGON', 'Универсал'), ('COUPE', 'Купе'), ('MINIVAN', 'Минивэн'), ('PICKUP', 'Пикап'), ('CABRIO', 'Кабриолет'), ('VAN', 'Фургон'), ('LIMOUSINE', 'Лимузин')], max_length=25, verbose_name='Тип кузова')),
                ('photo_link', models.URLField(verbose_name='Ссылка на фото')),
                ('start_year', models.IntegerField(verbose_name='Год начала производства')),
                ('end_year', models.IntegerField(verbose_name='Год конеца производства')),
                ('places', models.IntegerField(verbose_name='Количество мест')),
                ('average_price', models.IntegerField(blank=True, default=0, verbose_name='Средняя цена, руб.')),
                ('total', models.IntegerField(blank=True, default=0, verbose_name='Всего на рынке')),
            ],
            options={
                'db_table': 'car_generation',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255, verbose_name='Модель')),
                ('link_auto_ru', models.URLField(verbose_name='Ссылка на auto.ru')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.carbrand', verbose_name='Марка')),
            ],
            options={
                'db_table': 'car_model',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название региона')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='GenerationRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Количество')),
                ('average_price', models.IntegerField(verbose_name='Средняя цена в регионе')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.carmodel', verbose_name='Поколение')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.region', verbose_name='Регион')),
            ],
            options={
                'db_table': 'generation__region',
            },
        ),
        migrations.CreateModel(
            name='GenerationEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_type', models.CharField(choices=[('FORWARD_CONTROL', 'Передний'), ('REAR_DRIVE', 'Задний'), ('ALL_WHEEL_DRIVE', 'Полный')], max_length=20, verbose_name='Привод')),
                ('transmission_type', models.CharField(choices=[('AMT', 'Роботизированная'), ('AV', 'Автоматическая'), ('CVT', 'Вариатор'), ('MT', 'Механическая')], max_length=20, verbose_name='Коробка передач')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.carengine', verbose_name='Двигатель')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.cargeneration', verbose_name='Поколение')),
            ],
            options={
                'db_table': 'generation__engine',
            },
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.carmodel', verbose_name='Модель'),
        ),
    ]
