# Generated by Django 4.0.5 on 2022-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carengine',
            name='modification',
            field=models.CharField(default='', max_length=255, verbose_name='Модификация'),
            preserve_default=False,
        ),
    ]
