# Generated by Django 4.0.5 on 2022-07-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('total', models.IntegerField(verbose_name='Количество')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.carmodel', verbose_name='Поколение')),
            ],
        ),
    ]
