# Generated by Django 4.0.5 on 2022-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_carengine_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargeneration',
            name='auto_ru_link',
            field=models.URLField(default='', verbose_name='Ссылка на auto.ru'),
            preserve_default=False,
        ),
    ]
