# Generated by Django 4.0.5 on 2022-07-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_cargeneration_auto_ru_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargeneration',
            name='places',
        ),
    ]
